### PR TITLE
reconstructed this project and added example for visualize function

### PR DESCRIPTION
**Pull request by iamnotstone**
1. reconstructed this project for multiple examples . 
2. added visualize function for a better performance in some condition.

### CODE REVIEW

**Comment by donalffons** [comment]
Thanks a lot! This does look really nice. I just had a look at your code with the `visualize` function. If I understand correctly, your improvements with this function are:
- Less and easier to read code.
- Its easier and cleaner to use than the current `openCascadeHelper::tessellate` method.
- Its using ThreeJS BufferGeometries which are better for complex geometries with large number of polygons

I did a little bit of benchmarking and it seems like the overall performance of `visualize` (80-100ms for bottle example) compared to `openCascadeHelper::tessellate` (90-110ish) is a tiny bit better.

Do you think there are any drawbacks of `visualize` compared to `openCascadeHelper::tessellate`? Is there something missing? If its just better, we might just want to remove the old code...

**Comment by iamnotstone** [comment]
The ```visualize``` function generate multiple geometries which may lead to bad performance when there are a lot of (1000 +) objects for rendering(as there is a lot of ```draw``` calling for GPU). But it's good to simplify some raycasting applications. 
As the opencascade functions cost so many resources, I am now trying to using the opencascade.js with a web worker. In this situation, I think it's better for the ```visualize```  function to return buffers instead of geometries.

**Comment by iamnotstone** [comment]
And it's nice that you like my PR. I'll try to add a web-worker example later.

**Comment by donalffons** [comment]
Alright, I think in this case, its probably best to keep both implementations - at least for the moment. Neither of those implementations is universely better than the other. And if someone wants to build their own application based on opencascade.js, then at the moment there is a good chance that they might want to write their own tessellation anyways... So, I think those two implementations will hopefully give an overview on how this can be done.

I also rearranged things a bit more to avoid too much duplicate code. If you see any issues, please let me know.

A web-worker example would be very helpful, for sure! Realistically, you should never have such heavy code running on the main thread anyways, so setting up a web worker should be one of the first things you want to do when using opencascade.js. If you have more suggestions for example, keep them coming :slightly_smiling_face:.

**Pull request merged**
